global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
    - job_name: 'batch-processing-jmx'
      scrape_interval: 5s
      metrics_path: '/'
      static_configs:
        - targets: [ 'app:5555' ]  # порт JMX Exporter
