
services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - ./src/main/resources/schema-all.sql:/docker-entrypoint-initdb.d/schema-all.sql

  elasticsearch:
    image: elasticsearch:8.14.3
    platform: linux/amd64
    container_name: 'elasticsearch'
    restart: 'unless-stopped'
    volumes:
      - './elasticsearch/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
      - './elasticsearch/data:/usr/share/elasticsearch/data'
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: 'curl -f http://localhost:9200 || exit 1'

  logstash:
    image: logstash:8.14.3
    container_name: 'logstash'
    restart: 'unless-stopped'
    ports:
      - "5044:5044"
      - "5010:5000"
      - "9600:9600"
    volumes:
      - './logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro'
      - './logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro'
      - './logstash/pipelines:/usr/share/logstash/config/pipelines:ro'
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: 'kibana:8.14.3'
    container_name: 'kibana'
    restart: 'unless-stopped'
    volumes:
      - './kibana/conf.yml:/usr/share/kibana/config/kibana.yml:ro'
    ports:
      - '5601:5601'
#    environment:
#      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  filebeat:
    build: 'filebeat'
    container_name: 'filebeat'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/containers:/usr/share/dockerlogs/data:ro'
    depends_on:
      elasticsearch:
        condition: service_healthy
      logstash:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep filebeat"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: 'prom/prometheus:v3.4.0'
    container_name: 'prometheus'
    restart: 'unless-stopped'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]

  grafana:
    image: 'grafana/grafana:12.0.1'
    container_name: 'grafana'
    restart: 'unless-stopped'
    ports:
      - '3000:3000'
    environment:
      - 'GF_USERS_ALLOW_SIGN_UP=false'
    volumes:
      - './grafana/provisioning:/etc/grafana/provisioning'
    depends_on:
      - 'prometheus'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]

  app:
    depends_on:
      - postgresdb
      - filebeat
      - grafana
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5555:5555"
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"