input {
  beats { port => 5044 }
}

filter {
  if [log] {
    mutate {
      rename => { "[log][msg]" => "msg" }
      rename => { "[log][class]" => "class" }
      rename => { "[log][method]" => "method" }
      rename => { "[log][line]" => "line" }
      rename => { "[log][thread]" => "thread" }
      rename => { "[log][logger]" => "logger" }
      rename => { "[log][level]" => "level" }
      rename => { "[log][ts]" => "ts" }
      rename => { "[log][pid]" => "pid" }
      rename => { "[log][app]" => "app" }
      rename => { "[log][parentId]" => "parentId" }
      rename => { "[log][spanId]" => "spanId" }
      rename => { "[log][traceId]" => "traceId" }
    }

    if [log][http] {
      mutate {
        rename => { "[log][http][method]" => "http_method" }
        rename => { "[log][http][uri]" => "http_uri" }
      }
    }

    mutate {
      remove_field => ["log"]
    }
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
